### ISSUE TITLE
Work with IDE

### ISSUE THREAD

**Issue by kination** [grpc-ecosystem/polyglot#102]
Hello.

Which IDE do you use for working this project?
Because I'm trying to use intellij with bazel plugin, but it seems failing in loading project, so want to get more about it.

**Comment by dinowernli** [comment]
Last time I tried this worked fine with idea and the bazel plugin. Could
you share the exact steps you are taking and where you're running into
issues?

Also, what bazel and idea versions are you using? Does everything build for
you outside of the ide?

**Comment by kination** [comment]
Hello @dinowernli 
My bazel version is 0.12.0, and IntelliJ is 2018.1.2 CE, with bazel plugin.

I imported project with `.bazelproject` file, and loaded project 

![screen shot 2018-05-08 at 15 54 00](https://user-images.githubusercontent.com/1720209/39742345-1787ccc0-52d8-11e8-977e-3e51149ed3c6.png)

but it shows error in intellij as `Blaze problem`
```
Error:Cannot run program "bazel" (in directory "/Users/kwangin/workspace/polyglot"): error=2, No such file or directory
```

How's your side works?

**Comment by dinowernli** [comment]
This looks like your bazel plugin can't find your bazel binary. In the
bazel plugin settings, can you explicitly add a path to your bazel binary
and try again?

**Comment by kination** [comment]
@dinowernli Oh, thanks for guide!

Now it works after path fixed.
