### ISSUE TITLE
Capturing response

### ISSUE THREAD

**Issue by abnair24** [grpc-ecosystem/polyglot#103]
I would like to know how the output response can be written to file to convert to string format which can be manipulated for further testing.

Currently i am using polyglot as library in my project.

**Comment by dinowernli** [comment]
When using the polyglot binary, you can set where the output is going using the config: https://github.com/grpc-ecosystem/polyglot/blob/master/src/main/proto/config.proto#L87

If you're using bits of the polyglot code directly, you might want to look here: https://github.com/grpc-ecosystem/polyglot/blob/master/src/main/java/me/dinowernli/grpc/polyglot/io/Output.java#L38

Does that help?

**Comment by dinowernli** [comment]
Closing this up, please reopen if you feel there is any more action required.
