### ISSUE TITLE
Parsing Authorization fails

### ISSUE THREAD

**Issue by abnair24** [grpc-ecosystem/polyglot#104]
Hi,
I tried to pass auth token in below format:
--metadata="Authorization:Bearer <auth-token>" into polyglot command line args, which results in error as space after "Bearer" is not read properly.

Is there any other way to achieve the same

**Comment by dinowernli** [comment]
We should definitely fix polyglot to ignore the trailing space.

As a workaround, can you pass the argument without a space in the meanwhile?

**Comment by abnair24** [comment]
@dinowernli If i pass argument without space ,server returns as authorization failure

**Comment by dinowernli** [comment]
A few questions from my side:
* Is there any chance you could add your exact invocation of polyglot and the output you are seeing? That would make it easier to narrow down the issue.
* Your use case for passing a metadata value with a trailing space seems to be to pass an empty bearer token. Just curious, how come you need to do that? Is the recipient distinguishing the case of an empty bearer from the case of not passing any authorization header at all?

**Comment by jchoffmann** [comment]
I have the same problem, metadata key/value pairs that contain spaces fail to parse, which renders basic auth impossible. Example invocation:

`java -jar polyglot.jar --command=call --proto_discovery_root=<proto dir> --endpoint=<server> --metadata=Authorization:"Basic xyz" --full_method='<method>' <<< '<payload>'`

yields

> [main] INFO me.dinowernli.grpc.polyglot.Main - Polyglot version: 1.6.0
> Exception in thread "main" java.lang.RuntimeException: Unable to parse command line flags
>         at me.dinowernli.grpc.polyglot.Main.main(Main.java:33)
> Caused by: java.lang.IllegalArgumentException: Unable to parse command line flags
>         at me.dinowernli.grpc.polyglot.config.CommandLineArgs.parse(CommandLineArgs.java:120)
>         at me.dinowernli.grpc.polyglot.Main.main(Main.java:31)
> Caused by: org.kohsuke.args4j.CmdLineException: "--metadata=Authorization:Basic xyz" is not a valid option
>         at org.kohsuke.args4j.CmdLineParser.parseArgument(CmdLineParser.java:512)
>         at me.dinowernli.grpc.polyglot.config.CommandLineArgs.parse(CommandLineArgs.java:118)
>         ... 1 more

Other combinations of single quotes / double quotes around the value only as well as both key-value pair had the same result.

Removing the space passes parsing but then obviously fails service authentication.

**Comment by dinowernli** [comment]
I looked into the issue and it appears to be a problem with `args4j`. I have long-standing plans to switch to something like [jCommander](http://jcommander.org) or [flagz](https://github.com/mwitkow/java-flagz), which should fix this.

Don't really have an ETA yet for when I'll get around to switching things over though.

**Comment by jchoffmann** [comment]
I already had a quick look and could provide a first PR soon if you're OK with that.

**Comment by dinowernli** [comment]
@jchoffmann sounds great if you're up for it. Happy to stare at an early draft of a PR as well if that helps.

**Comment by jchoffmann** [comment]
@dinowernli Sure, first version is done and all tests are passing. Just need to do some cleaning up and will create the PR shortly.

**Comment by dinowernli** [comment]
This is now fixed at head since https://github.com/grpc-ecosystem/polyglot/pull/108.
