### ISSUE TITLE
Using proto text files instead of json

### ISSUE THREAD

**Issue by oferb** [grpc-ecosystem/polyglot#106]
Hey,
Is it possible to use proto text format as the request proto, instead of json?
This way, I can print proto to terminal, and use it directly with Polyglot, without having to convert it to json first.

Also, proto text format is easier to manually edit than jsons.

Thanks!

**Comment by dinowernli** [comment]
The current format relies on the fact that consecutive newlines can't appear inside json messages, allowing us to use consecutive newlines to separate elements in a stream of messages.

I'm not sure proto textformat give us the same guarantee. If they don't, I'm afraid we'd run into trouble representing a stream of textformat protos.

**Comment by oferb** [comment]
Not sure either.
If there is no such support in proto, perhaps we could support only one
message for proto? It's still highly useful.
