### ISSUE TITLE
How to build a polyglot.jar?

### ISSUE THREAD

**Issue by jchoffmann** [grpc-ecosystem/polyglot#107]
I followed the [building-a-binary](https://github.com/grpc-ecosystem/polyglot#building-a-binary) description and the bazel build finished with success.

I don't see a useful binary in the `./bazel-bin/src/main/java/me/dinowernli/grpc/polyglot` directory though, the resulting polyglot.jar is only 352 bytes and contains only a manifest file:

```
$ cd bazel-bin/src/main/java/me/dinowernli/grpc/polyglot
$ ls -l polyglot.jar
-r-xr-xr-x  1 jhoffmann  wheel  352 25 Aug 22:00 polyglot.jar
$ jar tfv polyglot.jar
     0 Fri Jan 01 00:00:00 CET 2010 META-INF/
   112 Fri Jan 01 00:00:00 CET 2010 META-INF/MANIFEST.MF
```

I don't know anything about bazel though and I have just copy/pasted the commands from the readme.  Am I doing something wrong? How can I build a fat jar?

**Comment by jchoffmann** [comment]
Bazel command for building a jar suitable for deployment (fat jar):
```
$ bazel build src/main/java/me/dinowernli/grpc/polyglot:polyglot_deploy.jar
```

**Comment by dinowernli** [comment]
Thanks, I've updated the project readme file.
