### ISSUE TITLE
Unable to compile latest master repo

### ISSUE THREAD

**Issue by kkdeepakkrish** [grpc-ecosystem/polyglot#112]
Hi,
I am trying to do some tests  by cloning the latest version of polyglot from the repo and building the project.
I am facing the below error

$ bazel build src/main/java/me/dinowernli/grpc/polyglot

INFO: Invocation ID: 09144027-0eb0-4e12-8ab0-bc6d3a4a86b1
ERROR: error loading package '': Encountered error while reading extension file 'repositories.bzl': no such package '@grpc_java//': The native http_archive rule is deprecated. load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive") for a drop-in replacement.
Use --incompatible_remove_native_http_archive=false to temporarily continue using the native rule.
ERROR: error loading package '': Encountered error while reading extension file 'repositories.bzl': no such package '@grpc_java//': The native http_archive rule is deprecated. load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive") for a drop-in replacement.
Use --incompatible_remove_native_http_archive=false to temporarily continue using the native rule.

Can someone help triage this?
Thanks!

**Comment by dinowernli** [comment]
Hi @kkdeepakkrish, Polyglot is confirmed to build with bazel 0.11.1 (see travis.yaml).

It shouldn't be too much work to modify Polyglot to build again with the latest bazel version, but I can't promise I'll get to it anytime soon (happy to accept patches though).

**Comment by dinowernli** [comment]
This is now done with https://github.com/grpc-ecosystem/polyglot/pull/114.
