### ISSUE TITLE
Add integration tests for TLS

### ISSUE THREAD

**Issue by mwitkow** [grpc-ecosystem/polyglot#12]
You can use the CA and TLS certificates + loaders from upstream `grpc-java`:

Loader:
https://github.com/grpc/grpc-java/blob/5c4817723e90b8adb8ed0cf923885df6301ed303/testing/src/main/java/io/grpc/testing/TestUtils.java#L220

Certs in here:
https://github.com/grpc/grpc-java/tree/5c4817723e90b8adb8ed0cf923885df6301ed303/testing/src/main/resources/certs

Usage:
https://github.com/grpc/grpc-java/blob/5c4817723e90b8adb8ed0cf923885df6301ed303/interop-testing/src/test/java/io/grpc/testing/integration/Http2NettyTest.java#L88

**Comment by dinowernli** [comment]
This has been resolved with https://github.com/dinowernli/polyglot/pull/27
