### ISSUE TITLE
Add support for JSON

### ISSUE THREAD

**Issue by mwitkow** [grpc-ecosystem/polyglot#13]
[text format](https://developers.google.com/protocol-buffers/docs/reference/cpp/google.protobuf.text_format#classes-in-this-file) seems to be dead and for `proto3` `jsonpb` seems to be the human-readable encoding of choice.

Please support JSON for proto3.

**Comment by dinowernli** [comment]
This is addressed in pull request https://github.com/dinowernli/polyglot/pull/16.
