### ISSUE TITLE
Make polyglot easy to use from scripts

### ISSUE THREAD

**Issue by mwitkow** [grpc-ecosystem/polyglot#14]
Many people use `\n` as a separator for multiple JSON objects in a single file. I think a `\n\n` would work for TextFormat of `proto2`.

Please support mulit-stream in and out for unary and streaming gRPC services. Basically:
- read from stdin, every time you read a whole message (suing `\n` or `\n\n` as separators)
- write responses in the format of choice to stdout
- output the [grpc response status](https://github.com/grpc/grpc-java/blob/master/core/src/main/java/io/grpc/Status.java) as a UNIX value of the program exit (OK maps nicely to `0`)
- print the `response status: <grpc status>: <grpc message>` to `stderr` if not `OK`
- print all exceptions and problems to `stderr`

This will make it easy to use polyglot in bash scripts by `cat`-ing output in, and processing output automatically

**Comment by dinowernli** [comment]
This has been partially implemented:
- Reading and writing streams of protos from \n\n-separated json files is now supported

**Comment by dinowernli** [comment]
Closing this in favor of the more fine-grained https://github.com/dinowernli/polyglot/issues/31 and https://github.com/dinowernli/polyglot/issues/32.
