### ISSUE TITLE
Add support for server reflection

### ISSUE THREAD

**Issue by mwitkow** [grpc-ecosystem/polyglot#37]
This will allow you to drop the need for a `.proto` reading locally, and just rely on the remote server.

Some caching of the results may be useful.
https://github.com/grpc/grpc-go/tree/master/reflection

Not yet available for Java
https://github.com/grpc/grpc-java/issues/651

**Comment by mwitkow** [comment]
https://github.com/grpc/grpc/blob/master/doc/server-reflection.md
for documentation of `grpc` main

**Comment by dinowernli** [comment]
This is done.
