### ISSUE TITLE
"no main manifest attribute, in polyglot.jar"

### ISSUE THREAD

**Issue by danielyli** [grpc-ecosystem/polyglot#51]
After building the JAR via `$ bazel build src/main/java/me/dinowernli/grpc/polyglot` and running via `java -jar polyglot.jar ...`, I get this error:

    no main manifest attribute, in polyglot.jar

This is after a fresh Bazel installation on Mac with latest Java.

**Comment by danielyli** [comment]
This seems to be a readme documentation issue.  Probably should clarify when to use `java -jar polyglot.jar` and when to use `./polyglot`.

**Comment by dinowernli** [comment]
Hmm, just re-read the readme and it does explain when to use `./polyglot.jar` and when to use `java -jar polyglot.jar`.

If you still think it is confusing, would you mind suggesting a change? Perhaps even as PR?

**Comment by peteboothroyd** [comment]
To create a deployable jar the following command run from the root of the workspace seems to do the trick.

```bazel build src/main/java/me/dinowernli/grpc/polyglot:polyglot_deploy.jar```

Hope this helps anyone else looking.
