### ISSUE TITLE
How to build config.proto jar?

### ISSUE THREAD

**Issue by nykolaslima** [grpc-ecosystem/polyglot#70]
I'm trying to create a PR about supporting `grpc metadata`. I changed the `config.proto` file but I'm unable to generate the `ConfigProto.class` from my change.

What's the bazel task to do it?

**Comment by dinowernli** [comment]
Given that you've managed to send the other PR, I'm assuming this ended up working out. Each proto has a Bazel build rule you can build, at which point the proto compiler gets invoked to produce the generated code.
