### ISSUE TITLE
Add documentation on logging

### ISSUE THREAD

**Issue by gfecher** [grpc-ecosystem/polyglot#84]
Hi,

It would be great if you could add a paragraph about logging to the README.md file.
Something along the lines of this:

Polyglot uses the `slf4j` logging framework with the `org.slf4j.impl.SimpleLogger` implementation. It also redirects gRPC's JUL logs to slf4j. To change the default log level, specify the `org.slf4j.simpleLogger.defaultLogLevel` JVM argument, e.g. `-Dorg.slf4j.simpleLogger.defaultLogLevel=debug`.

Many thanks,
Feso

**Comment by dinowernli** [comment]
Thanks a lot, I have used some of your copy almost verbatim.

**Comment by gfecher** [comment]
Thank you!
